project:
  title: "AB Testing"
  type: website
  output-dir: ../docs

format:
  html:
    code-fold: true
    html-math-method: katex
  revealjs:
    theme: [default, evelyn.scss]
    css: evelyn.css
    logo: 'img/techfirstlogo.png'
    footer: " Taste of IT Conference "
    scrollable: true
    transition: slide
    transition-speed: fast
    
    chalkboard:
      buttons: true

execute:
  echo: true
  output: true
  error: true

jupyter: python3


